title: Sample GitHub Page
author: XofK
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This description is a description of my sample page created in GitHub.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
